---

- name: "{{ role_name }} | install package"
  tags:
  - package
  package:
    name: 
    - "{{ service_name }}"
    state: latest

- name: "{{ role_name }} | firewall config dir"
  file:
    path: "{{ softether_iptables_conf | dirname }}"
    state: directory

- name: "{{ role_name }} | firewall config"
  tags:
  - config
  - iptables
  template:
    src: "{{ item | basename }}.j2"
    dest: "{{ item }}"
  loop:
  - "{{ softether_iptables_conf }}"
  notify:
  - daemon-reload
  - restart {{ role_name }}

- name: "{{ role_name }} | service"
  tags:
  - service
  service:
    name: "{{ service_name }}"
    state: started
    enabled: yes
