#! /usr/bin/env ansible-playbook
# Uninstall role
# Run prior to removing host from inventory groups, so hostvars are accessible
---
- name: softether-server | uninstall
  hosts: softether_server
  tasks:
  - include_role:
      name: softether-server
      tasks_from: uninstall.yml
